source 'https://rubygems.org'
ruby '3.1.2'

gem 'sinatra',            '1.4.8'
gem 'data_mapper',        '1.2.0'
gem 'dm-postgres-adapter',  '1.2.0'
gem 'json',               '1.8.6'
gem 'pg', '1.4.5'
gem 'curb', '1.0.1'
gem 'compass', '1.0.3'